# ============================================================
# OLED
# ============================================================

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y


# ============================================================
# BATTERY
# ============================================================

CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60


# ============================================================
# BLUETOOTH
# ============================================================

# 5 dispositivos Bluetooth + 1 conexión para la otra mitad
CONFIG_BT_MAX_CONN=6
CONFIG_BT_MAX_PAIRED=6


# ============================================================
# RGB UNDERGLOW
# ============================================================

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y