name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: zmkfirmware/zmk-build-arm:4.1

    name: Build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      # ============================================================
      # CORNE LEFT
      # ============================================================

      - name: West Build (Corne Left)
        run: |
          west build \
            -s zmk/app \
            -b nrfmicro/nrf52840/zmk \
            -- \
            -DSHIELD=corne_left \
            -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
            -DDTC_OVERLAY_FILE="${GITHUB_WORKSPACE}/config/corne_rgb.overlay"

      - name: Corne Left DTS
        if: always()
        run: |
          if [ -f build/zephyr/nrfmicro_nrf52840_zmk.dts.pre.tmp ]; then
            cat -n build/zephyr/nrfmicro_nrf52840_zmk.dts.pre.tmp
          elif [ -f build/zephyr/nrfmicro_13.dts.pre.tmp ]; then
            cat -n build/zephyr/nrfmicro_13.dts.pre.tmp
          else
            echo "DTS file not found"
          fi

      - name: Corne Left Kconfig
        if: always()
        run: |
          if [ -f build/zephyr/.config ]; then
            cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
          else
            echo "Kconfig file not found"
          fi

      - name: Rename left firmware
        run: |
          cp build/zephyr/zmk.uf2 corne_left_nrfmicro.uf2

      - name: Upload left firmware
        uses: actions/upload-artifact@v4
        with:
          name: corne-left-firmware
          path: corne_left_nrfmicro.uf2

      # ============================================================
      # CORNE RIGHT
      # ============================================================

      - name: West Build (Corne Right)
        run: |
          west build \
            --pristine \
            -s zmk/app \
            -b nrfmicro/nrf52840/zmk \
            -- \
            -DSHIELD=corne_right \
            -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
            -DDTC_OVERLAY_FILE="${GITHUB_WORKSPACE}/config/corne_rgb.overlay"

      - name: Corne Right DTS
        if: always()
        run: |
          if [ -f build/zephyr/nrfmicro_nrf52840_zmk.dts.pre.tmp ]; then
            cat -n build/zephyr/nrfmicro_nrf52840_zmk.dts.pre.tmp
          elif [ -f build/zephyr/nrfmicro_13.dts.pre.tmp ]; then
            cat -n build/zephyr/nrfmicro_13.dts.pre.tmp
          else
            echo "DTS file not found"
          fi

      - name: Corne Right Kconfig
        if: always()
        run: |
          if [ -f build/zephyr/.config ]; then
            cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
          else
            echo "Kconfig file not found"
          fi

      - name: Rename right firmware
        run: |
          cp build/zephyr/zmk.uf2 corne_right_nrfmicro.uf2

      - name: Upload right firmware
        uses: actions/upload-artifact@v4
        with:
          name: corne-right-firmware
          path: corne_right_nrfmicro.uf2